name: Ingest MCP Tool

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ingest_tool]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "GitHub Actions is working!"